### ISSUE TITLE
Incorrect dependencies for v1.3.0

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/flask-restx-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The requirements for this package in conda-forge do not match those of the `requirements/install.pip` file in the Github repo.  There are several significant changes from v1.2.0 (like flask v3 support).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by xhochy** [comment]
@DManowitz I think the best way forward would also be if you submit a PR to this feedstock that fixes these dependencies. Only reporting an issue typically doesn't solve it that fast

**Comment by DManowitz** [comment]
That was going to be my next step.  I generally wait a day or so to see if the maintainers want to do a PR themselves or want me to do it.
