### ISSUE TITLE
v0.2.0 not merged

### ISSUE THREAD

**Issue by maresb** [conda-forge/flask-restx-feedstock#9]
Any particular reason for holding back v0.2.0?

**Comment by SVilgelm** [comment]
There is an error in GitHub action, which should create the proper PR, I still didn't fix it. I will have a time probably tomorrow or day after tomorrow to work on it

**Comment by mcguipat** [comment]
Any progress here?

**Comment by fhoehle** [comment]
@SVilgelm Is there any update available?

**Comment by xhochy** [comment]
@fhoehle @mcguipat Please make a PR for 0.2.0 and add yourself as a maintainer, then I'll merge.

**Comment by xhochy** [comment]
@SVilgelm There shouldn't be a need for a separate bot, the regro-cf-autotick-bot will also learn to update Python dependencies in the next weeks. This should enable full automation on the conda-forge side for Python packages (opt-in).
